### PR TITLE
Update telegram-client.rst

### PR DESCRIPTION
**Pull request by fquinto**
Typo error: change this "download_profile_method" to this "download_profile_photo"

### CODE REVIEW

**Comment by Lonami** [comment]
Nice catch. We can leave this open for a while in case you find more mistakes. I generally dislike tiny docs commits like this.

**Comment by fquinto** [comment]
> We can leave this open for a while in case you find more mistakes.

ok!

> I generally dislike tiny docs commits like this.

Yes... sorry for that! :)

Congrats for your documentation, nice to have.

**Comment by Lonami** [comment]
We should address https://github.com/LonamiWebs/Telethon/issues/990#issuecomment-419982186 too. I knew there would be other mistakes.

**Comment by Lonami** [comment]
Pushed a commit with more changes, thanks for letting me know about the mistake though!

**Pull request closed without merging**
