### PR TITLE
Update API schema

### PR DESCRIPTION
**Pull request by udf**
telegramdesktop/tdesktop@35356a17363b351f149e68b9e2dce939d7a7302a

### CODE REVIEW

**Comment by Lonami** [comment]
Yeah they keep changing this after-release but I'm gonna hold off until v2 is out before merging anything new.

**Comment by udf** [comment]
Will we get v2 before Vail's out?

**Comment by Lonami** [comment]
[There's a good chance.](https://github.com/LonamiWebs/Telethon/tree/v2)

**Comment by Lonami** [comment]
Superseded by #3157.

**Pull request closed without merging**
