### PR TITLE
Support easily deleting all messages from a user

### PR DESCRIPTION
**Pull request by Ak4zh**
Added friendly method to delete user message history from a supergroup.

Resolved: #1318

### CODE REVIEW

**Comment by Lonami** [comment]
Hm... I wonder if this is a good addition. When I made the issue I had in mind that this would have a less confusing name, but given how trivial it is to use, I wonder if it's worth just adding it to the documentation? I mean, the complexity is not that different from the two:

```python
await client.delete_user_messages(chat, user)
# vs
await client(functions.channels.DeleteUserHistoryRequest(chat, user))
```

I'd also like to bikeshed on the name. Is it a good idea to have a separate method instead of reusing `delete_messages`?

**Comment by Ak4zh** [comment]
Considering `delete_messages` is available in all chat type and for both user account and bot account but `DeleteUserHistory` is only available for user account and in a specific chat type it may be slight inconsistent.

But yeah you can simply add the raw api call in documentatiom instead.

**Comment by Lonami** [comment]
With small group chats or private conversations we could iterate over all messages and delete them all, but this could also be done in this new method. This would make the friendly method more useful, but I'm not sure if it's something I want to do.

**Comment by Lonami** [comment]
I'm gonna close this because for the time being I have changed my mind and don't think this is necessary. Thanks for the effort, though.

**Pull request closed without merging**
