### PR TITLE
Added id property

### PR DESCRIPTION
**Pull request by ferferga**
To make obtaining the id of an incoming message easier.

### CODE REVIEW

**Comment by Lonami** [comment]
`event.id` is somewhat misleading. Is the ID of the event itself? The chat? Sender? See the property above, `out` is also short and straightforward, but it's clear the event is `out` (outgoing). No ambiguity here.

**Comment by expectocode** [comment]
Yeah, a better attribute name would be message_id but then may as well use message.id

**Comment by Lonami** [comment]
That should be enough arguments. I appreciate the interest though.

**Comment by expectocode** [comment]
PS a small note, commit messages should start with a word like Add rather than Added

**Pull request closed without merging**
