### PR TITLE
(Add) Add to_dict() method

### PR DESCRIPTION
**Pull request by Goblenus**
This commit adds to_dict() method, and you can build dict object from each tl object.

Method samples:
```
def to_dict(self):
        return {
        'pinned': self.pinned, 
        'peer': self.peer.to_dict() if self.peer is not None else None, 
        'top_message': self.top_message, 
        'read_inbox_max_id': self.read_inbox_max_id, 
        'read_outbox_max_id': self.read_outbox_max_id, 
        'unread_count': self.unread_count, 
        'notify_settings': self.notify_settings.to_dict() if self.notify_settings is not None else None, 
        'pts': self.pts, 
        'draft': self.draft.to_dict() if self.draft is not None else None, 
        }
```

```
def to_dict(self):
        return {
        'messages': [_.to_dict() if _ is not None else None for _ in self.messages] if self.messages is not None else [],
        'chats': [_.to_dict() if _ is not None else None for _ in self.chats] if self.chats is not None else [],
        'users': [_.to_dict() if _ is not None else None for _ in self.users] if self.users is not None else [],
        }

```

### CODE REVIEW

**Comment by Lonami** [comment]
`_` (underscore) is often used to ignore a value, for instance:
```python
_, entities = client.get_dialogs()
```

It would be better if you changed it for, say, `x`.

Besides this, it looks fine although I cannot test it. I agree it would make it easier to serialize everything as JSON (probably what you need), although accessing the `.__dict__` perhaps would have been enough.

**Comment by Goblenus** [comment]
It may be tricky to serialize it to json. Tl object has bytes, datetime types, that can't serialize easely. In my project i use default handler (from json module) to serialize bytes to base64 string and datetime to string format, others may prefer other methods.

**Comment by Goblenus** [comment]
```
It would be better if you changed it for, say, x.
```

Done.

**Comment by Lonami** [comment]
Looks good to me, thanks!

**Pull request merged**
