### PR TITLE
Generate TL modules after installing package in development mode.

### PR DESCRIPTION
**Pull request by andreif**
I did not fix all issues via #384. This one should do it.

### CODE REVIEW

**Comment by andreif** [comment]
Hm, wait, still broken.

**Comment by andreif** [comment]
Or maybe it will work once packaged. The only thing which does not work is installing by github URL:

```
pip install git+https://github.com/andreif/Telethon.git@b02ed7c
```

This is due to generation of tl types in git repo, not the final package directory.

**Comment by andreif** [comment]
I can try testing install from PyPI but I think we have to fix the installing by url as well.

**Comment by andreif** [comment]
Gotcha, such installing was broken before #384:
```
pip install git+https://github.com/LonamiWebs/Telethon.git@e48f15be80e592be64a7e11b1eda8980d5b3657b
```
so it's fine to merge this one.

**Comment by Lonami** [comment]
Could you explain what both `Develop` and `Install` classes do exactly? I assume they're steps but I'd like to know more. How are they triggered and when?

**Comment by andreif** [comment]
`setup.py develop` installs package without copying package files to `site-packages` directory of your virtualenv, while `setup.py install` does that.

**Comment by andreif** [comment]
I'll try to package and see if installing from PyPI is also broken now

**Comment by andreif** [comment]
@Lonami BTW, do you release with or without TL types?

**Comment by Lonami** [comment]
I push to PyPi with everything generated.

**Comment by andreif** [comment]
If you release with everything generated, then it will obviously not fail.

**Comment by andreif** [comment]
You should probably mention it in readme, that one has to run `setup.py gen_tl` after installing from source (i.e. not `develop`).

**Comment by Lonami** [comment]
@andreif I mention that on the wiki :P

**Comment by andreif** [comment]
LOL, this does not always work, see #390 😛

**Comment by andreif** [comment]
Oh, did I misunderstood what #390 is about?

**Comment by Lonami** [comment]
Yeah probably. #390 seems to be a weird bug with "qpython". Not sure what it even is.

**Comment by andreif** [comment]
Okay, fast reading is not my thing then, apologies.

**Comment by andreif** [comment]
I can remove install part from here, so that develop will always auto-generate TL types, but not install. Ok?

**Comment by Lonami** [comment]
I don't know how this works so I'm counting on you that this will fix it :)

**Comment by andreif** [comment]
It would be nice to find a way to generate them even for normal install. I often install packages from forks specified as git URL.

**Comment by andreif** [comment]
You can merge it. I doubt we can find an easy way to generate the files for install and it's usually packaged with them.

**Comment by Lonami** [comment]
Another approach would be to embed the `.tl` file in the package and the `telethon_generator` too, and generate everything when importing if they aren't found. But it may not work because write permission and stuff.

**Comment by Lonami** [comment]
Not necessary since installing also generates files if cloned from GitHub. Not sure when that was added (sorry) and going through old PRs now.

**Pull request closed without merging**
