### PR TITLE
Exclude empty first_name in get_display_name

### PR DESCRIPTION
**Pull request by feodoran**
Users may not have set first_name, but last_name only. This commit will remove None from the display name.

### CODE REVIEW

**Comment by Lonami** [comment]
Hm… how about something like:
```python
if entity.first_name:
    if entity.last_name:
        return '{} {}'.format(entity.first_name, entity.last_name)
    else:
        return entity.first_name
elif entity.last_name:
      return entity.last_name
else:
    return '(No name)'
```

You know, simply a matter of style. Sounds more natural that the first name is the first one we check :p

**Comment by feodoran** [comment]
I was going for less lines and better overview. But I like the (No Name).

**Comment by Lonami** [comment]
> I was going for less lines

As long as it's not 100 lines to simply determine the name, I will be okay with it.

> But I like the (No Name).

I'll wait for you to make the change then.

**Comment by feodoran** [comment]
I added the (No Name), but kept the structure. I thinks it is much easier to read this way, since there are no further nested ifs.

**Pull request merged**
