### PR TITLE
Enhanced flow

### PR DESCRIPTION
**Pull request by SmartManoj**
Enhanced flow if two-steps verification is enabled

### CODE REVIEW

**Comment by Lonami** [comment]
We already have `start()` for this, there is no need to clutter `sign_in` with the same logic, since it is the manual method for the sign in flow. People should generally prefer `start()` unless they need more control.

**Comment by SmartManoj** [comment]
then 
telethon.errors.rpc_errors_401.SessionPasswordNeededError: (SessionPasswordNeededError
(...), 'Two-steps verification is enabled and a password is required.')
But it is not an error. Is it?
It should tell to use client.sign_in(password=PASS) if 2FA enabled;

**Comment by Lonami** [comment]
It tells to use `password` already:
https://github.com/LonamiWebs/Telethon/blob/48d6f1585080ffce8d564fe4f4fda177f14153a2/telethon/client/auth.py#L288-L290

> should be used if a previous call raised

**Comment by SmartManoj** [comment]
if code and password is used 
client2.sign_in(num2, input('Enter code'),password=pwd) , it should raise error too.
Both params should be exclusive

**Pull request closed without merging**
