### PR TITLE
Redis session storage support

### PR DESCRIPTION
**Pull request by ezdev128**

### CODE REVIEW

**Comment by Lonami** [comment]
Thanks for the effort but the problem with this is that then I would be (or at least feel) responsible for maintaining this code. I'm not even sure if the Alchemy session is a good idea. I thought of having a separate project that held many kind of sessions for people to install and use, but I don't want to maintain it.

**Comment by Lonami** [comment]
I'm going to please ask you to keep this as your own repository (if you will, of course) You will be listed in the documentation (see #698) so that people can refer to you. Thanks! Tell me what you think.

**Comment by ezdev128** [comment]
No problem, I did it already.
Thanks!

**Comment by tulir** [comment]
What @Lonami meant is that you can put your Redis session implementation in its own repository that can be added as a dependency to projects that want a redis session. You can look at my [telethon-session-sqlalchemy](https://github.com/tulir/telethon-session-sqlalchemy) for an example of what I mean. If you do that, the repo can be added to the list of community session implementations added in #698.

**Comment by ezdev128** [comment]
@tulir 
https://github.com/ezdev128/telethon-session-redis
Thanks!

**Pull request closed without merging**
