### PR TITLE
Update PUSH register to layer 75

### PR DESCRIPTION
**Pull request by georgsh**
At least it worked for me, while old schema doesn't.
I found this schema update in pyrogram repo.

### CODE REVIEW

**Comment by Lonami** [comment]
I can't find said commit on Dan's repository. I doubt this is layer 75 but rather a fix for 74?

**Comment by delivrance** [comment]
Here you go: [Update to Layer 75](https://github.com/pyrogram/pyrogram/commit/ea35fa24801e6767c6fd37e4221abb5abafdbbc9)

**Comment by Lonami** [comment]
@delivrance that changed way more things and you only comitted a subset. Why?

**Comment by Lonami** [comment]
Not sure why he comitted only a subset then.

**Pull request closed without merging**
