### PR TITLE
Check is_creator for Chats, not only channels

### PR DESCRIPTION
**Pull request by apepenkov**
I commented it on original pr #1575  , but it's not in code so

### CODE REVIEW

**Comment by kolay-v** [comment]
looks like i missed creator check for chat

**Comment by apepenkov** [comment]
yea

**Comment by kolay-v** [comment]
and also i want mention here https://github.com/LonamiWebs/Telethon/pull/1575#discussion_r499155179

**Comment by Lonami** [comment]
> and also i want mention here #1575 (comment)

Replied there, but for completeness I'll repeat: it's autogenerated (not committed to the repo, but exists on a valid Telethon install).

**Pull request merged**
