### PR TITLE
fix UserWarning

### PR DESCRIPTION
**Pull request by penn5**

### CODE REVIEW

**Review by Lonami — CHANGES_REQUESTED** [review]
I guess this fixes an explicit `phone=None`, but why not use `utils.parse_phone`?

**Comment by penn5** [comment]
ok fair

**Comment by Lonami** [comment]
Could you let me know what code causes this so I can write a proper commit message?

**Comment by penn5** [comment]
Even having a + at the start of the passed phone number causes it

**Comment by Lonami** [comment]
I think I tried moving things around to parse before but decided against it and then I never actually parsed it. Double-parse should be fine.

**Pull request merged**
