### PR TITLE
/ Command and Welcome message in bot 

### PR DESCRIPTION
**Pull request by SmartManoj**

### CODE REVIEW

**Comment by Lonami** [comment]
Thanks, but the bot is good as-is. It is not intended for use in private, only for it to assist people in the groups.

**Comment by SmartManoj** [comment]
What about slash commands?

**Comment by SmartManoj** [comment]
They get docs quickly .
She should tell common problems.
In group they  said `you couldn't test bot here.`

**Comment by Lonami** [comment]
There is no need for slash commands, hashtags work fine. The documentation has sections with summaries for the most common methods most people need. Messaging a bot in private and learning how it works is more annoying than just asking in a group with real people.

**Pull request closed without merging**
