### PR TITLE
 Fix: Resend requests on BadServerSalt and BadMsgNotification

### PR DESCRIPTION
**Pull request by andr-04**
Propagated from my asyncio draft. Doesn't checked.

### CODE REVIEW

**Comment by Lonami** [comment]
Hm, interesting approach, wouldn't have thought of this. I'd like to add some explanatory comments before merging though.

**Comment by andr-04** [comment]
Hmm... Let's try to guess. You were going to make new dictionary `_pending_containers` in `MtProtoSender` and try to maintain it in actual state on `send` and `receive` and somewhere else, right? And, of course, this _somewhere else_ will give you new bugs.

I prefer to keep it simple. It's not very often happens, so iterating through a whole `_pending_receive` dictionary will not take a lot of resources.

**Comment by Lonami** [comment]
Yes, I like this approach. I just need a few explanatory comments for future readers (and myself).

**Comment by andr-04** [comment]
To tell the truth I don't read your large comments -- I read the code. It's more important to write a clear code instead of making a lot of tricks and describing them. Even if it a little more effective.

Yes, there is a feature of MTProto and can be described there.

**Comment by Lonami** [comment]
> write a clear code instead of making a lot of tricks and describing them

Yes, but the code can't explain *why* it's done a certain way, only *how* it's done. This isnt helpful for people studying the library for their own applications, or again, our future selves.

**Pull request merged**
