### PR TITLE
Add startup script for simple use

### PR DESCRIPTION
**Pull request by kyasabu**
**Hello**
I created a simple autostart script so that beginners can get started much quicker with Telethon! In fact it is so easy that they don't even need to read the documentation 🐱 

It does not yet work on windows, however I am sure (very) that it run perfect on Linux 🤘 
Hopefully someone will port my work to windows one day.

This is my first open source contribution, so please *don't* be mean ☺️ 

and yes I am very **proficient** at python language (self-thought and looking forward to get a job at **Google**) 
So if you need any help from me from me please contact me 😄

### CODE REVIEW

**Comment by Lonami** [comment]
Oops, I clicked the wrong button and I don't know how to merge now. Sorry buddy.

**Comment by kyasabu** [comment]
@cher-nov can help you with that

**Comment by cher-nov** [comment]
It's still invalid and contains no actual Python code. Sorry.

**Comment by danog** [comment]
Excuse me sir but this is blasphemy

TL markup instead of glorious python code

Please kys asap kthxbye

**Pull request closed without merging**
