### PR TITLE
Fix MTProtoState to check if remote msg_id is correct (#3753)

### PR DESCRIPTION
**Pull request by ih3xcode**

### CODE REVIEW

**Comment by Lonami** [comment]
This fix is not enough. I am working on adding the checks described in https://core.telegram.org/mtproto/security_guidelines#checking-msg-id and will push a fix in a moment.

Furthermore, master is not ready to be released any time soon, so I'll do this in the v1.24 branch instead.

**Comment by Thoufak** [comment]
@Lonami, could you please update the master? I'm curious to see how it goes, even if it's not usable and/or polished yet. Or maybe push to some other branch if you want.

**Comment by Lonami** [comment]
Master is the future v2 which is not ready at all currently. It's unlikely to work for anything larger than toy examples. I am pushing this fix to the v1.24 branch instead.

**Comment by Thoufak** [comment]
I understand. The reason I want to see the recent commits is that I'm making some changes to v1.24 for my personal usage. I've studied the code in master and I can see some improvements that I can port to 1.24 (purely for myself and by myself, no obligation for you).

Maybe there're some other nerdy fans of Telethon who will find it interesting and useful too :)

**Pull request closed without merging**
