### PR TITLE
Added some sticker related errors

### PR DESCRIPTION
**Pull request by teidesu**

### CODE REVIEW

**Comment by Lonami** [comment]
Thanks. Could you also update the `methods.csv` file?

While we're at it, there's a few more:
* USERPIC_UPLOAD_REQUIRED (caused by GetLocatedRequest) (https://t.me/TelethonChat/334367)
* TMP_PASSWORD_INVALID (probably 400), needs to regenerate the password auth (reported in a private chat)

**Comment by teidesu** [comment]
Sorry for 3 commits, web editor is pretty unusable :D

**Comment by Lonami** [comment]
Please add ` USERPIC_UPLOAD_REQUIRED,400,You must have a profile picture before using this method` to `errors.csv`.

**Comment by Lonami** [comment]
Thanks.

**Pull request merged**
